// replaces special characters with HTML entities
SpawEditor.prototype.convertToEntities = function(src_string)
{
  var result = src_string;
  
  var entities = {
    // Latin-1
    "ВЎ":"&iexcl;",
    "Вў":"&cent;",
    "ВЈ":"&pound;",
    "В¤":"&curren;",
    "ВҐ":"&yen;",
    "В¦":"&brvbar;",
    "В§":"&sect;",
    "ВЁ":"&uml;",
    "В©":"&copy;",
    "ВЄ":"&ordf;",
    "В«":"&laquo;",
    "В¬":"&not;",
    "В­":"&shy;",
    "В®":"&reg;",
    "ВЇ":"&macr;",
    "В°":"&deg;",
    "В±":"&plusmn;",
    "ВІ":"&sup2;",
    "Ві":"&sup3;",
    "Вґ":"&acute;",
    "Вµ":"&micro;",
    "В¶":"&para;",
    "В·":"&middot;",
    "Вё":"&cedil;",
    "В№":"&sup1;",
    "Вє":"&ordm;",
    "В»":"&raquo;",
    "Вј":"&frac14;",
    "ВЅ":"&frac12;",
    "Вѕ":"&frac34;",
    "Вї":"&iquest;",
    "ГЂ":"&Agrave;",
    "ГЃ":"&Aacute;",
    "Г‚":"&Acirc;",
    "Гѓ":"&Atilde;",
    "Г„":"&Auml;",
    "Г…":"&Aring;",
    "Г†":"&AElig;",
    "Г‡":"&Ccedil;",
    "Г€":"&Egrave;",
    "Г‰":"&Eacute;",
    "ГЉ":"&Ecirc;",
    "Г‹":"&Euml;",
    "ГЊ":"&Igrave;",
    "ГЌ":"&Iacute;",
    "ГЋ":"&Icirc;",
    "ГЏ":"&Iuml;",
    "Гђ":"&ETH;",
    "Г‘":"&Ntilde;",
    "Г’":"&Ograve;",
    "Г“":"&Oacute;",
    "Г”":"&Ocirc;",
    "Г•":"&Otilde;",
    "Г–":"&Ouml;",
    "Г—":"&times;",
    "Г":"&Oslash;",
    "Г™":"&Ugrave;",
    "Гљ":"&Uacute;",
    "Г›":"&Ucirc;",
    "Гњ":"&Uuml;",
    "Гќ":"&Yacute;",
    "Гћ":"&THORN;",
    "Гџ":"&szlig;",
    "Г ":"&agrave;",
    "ГЎ":"&aacute;",
    "Гў":"&acirc;",
    "ГЈ":"&atilde;",
    "Г¤":"&auml;",
    "ГҐ":"&aring;",
    "Г¦":"&aelig;",
    "Г§":"&ccedil;",
    "ГЁ":"&egrave;",
    "Г©":"&eacute;",
    "ГЄ":"&ecirc;",
    "Г«":"&euml;",
    "Г¬":"&igrave;",
    "Г­":"&iacute;",
    "Г®":"&icirc;",
    "ГЇ":"&iuml;",
    "Г°":"&eth;",
    "Г±":"&ntilde;",
    "ГІ":"&ograve;",
    "Гі":"&oacute;",
    "Гґ":"&ocirc;",
    "Гµ":"&otilde;",
    "Г¶":"&ouml;",
    "Г·":"&divide;",
    "Гё":"&oslash;",
    "Г№":"&ugrave;",
    "Гє":"&uacute;",
    "Г»":"&ucirc;",
    "Гј":"&uuml;",
    "ГЅ":"&yacute;",
    "Гѕ":"&thorn;",
    "Гї":"&yuml;",
    // symbols and greek
    "Ж’":"&fnof;",
    "О‘":"&Alpha;",
    "О’":"&Beta;",
    "Оі":"&Gamma;",
    "О”":"&Delta;",
    "О•":"&Epsilon;",
    "О–":"&Zeta;",
    "О—":"&Eta;",
    "О":"&Theta;",
    "О™":"&Iota;",
    "Ољ":"&Kappa;",
    "О›":"&Lambda;",
    "Оњ":"&Mu;",
    "Оќ":"&Nu;",
    "Оћ":"&Xi;",
    "Оџ":"&Omicron;",
    "О ":"&Pi;",
    "ОЎ":"&Rho;",
    "ОЈ":"&Sigma;",
    "О¤":"&Tau;",
    "ОҐ":"&Upsilon;",
    "О¦":"&Phi;",
    "О§":"&Chi;",
    "ОЁ":"&Psi;",
    "О©":"&Omega;",
    "О±":"&alpha;",
    "ОІ":"&beta;",
    "Оі":"&gamma;",
    "Оґ":"&delta;",
    "Оµ":"&epsilon;",
    "О¶":"&zeta;",
    "О·":"&eta;",
    "Оё":"&theta;",
    "О№":"&iota;",
    "Оє":"&kappa;",
    "О»":"&lambda;",
    "Ој":"&mu;",
    "ОЅ":"&nu;",
    "Оѕ":"&xi;",
    "Ої":"&omicron;",
    "ПЂ":"&pi;",
    "ПЃ":"&rho;",
    "П‚":"&sigmaf;",
    "Пѓ":"&sigma;",
    "П„":"&tau;",
    "П…":"&upsilon;",
    "П†":"&phi;",
    "П‡":"&chi;",
    "П€":"&psi;",
    "П‰":"&omega;",
    "вЂў":"&bull;",
    "вЂ¦":"&hellip;",
    "вЂІ":"&prime;",
    "вЂі":"&Prime;",
    "вЂѕ":"&oline;",
    "вЃ„":"&frasl;",
    "в„":"&weierp;",
    "в„‘":"&image;",
    "в„њ":"&real;",
    "в„ў":"&trade;",
    "в„µ":"&alefsym;",
    "в†ђ":"&larr;",
    "в†‘":"&uarr;",
    "в†’":"&rarr;",
    "в†“":"&darr;",
    "в†”":"&harr;",
    "в†µ":"&crarr;",
    "в‡ђ":"&lArr;",
    "в‡‘":"&uArr;",
    "в‡’":"&rArr;",
    "в‡”":"&hArr;",
    "в€Ђ":"&forall;",
    "в€‚":"&part;",
    "в€ѓ":"&exist;",
    "в€…":"&empty;",
    "в€‡":"&nabla;",
    "в€€":"&isin;",
    "в€‰":"&notin;",
    "в€‹":"&ni;",
    "в€Џ":"&prod;",
    "в€‘":"&sum;",
    "в€’":"&minus;",
    "в€—":"&lowast;",
    "в€љ":"&radic;",
    "в€ќ":"&prop;",
    "в€ћ":"&infin;",
    "в€§":"&and;",
    "в€Ё":"&or;",
    "в€©":"&cap;",
    "в€Є":"&cup;",
    "в€«":"&int;",
    "в‰…":"&cong;",
    "в‰€":"&asymp;",
    "в‰ ":"&ne;",
    "в‰Ў":"&equiv;",
    "в‰¤":"&le;",
    "в‰Ґ":"&ge;",
    "вЉ‚":"&sub;",
    "вЉѓ":"&sup;",
    "вЉ„":"&nsub;",
    "вЉ†":"&sube;",
    "вЉ‡":"&supe;",
    "вЉ•":"&oplus;",
    "вЉ—":"&otimes;",
    "вЉҐ":"&perp;",
    "в‹…":"&sdot;",
    "вЊ€":"&lceil;",
    "вЊ‰":"&rceil;",
    "вЊЉ":"&lfloor;",
    "вЊ‹":"&rfloor;",
    "вЊ©":"&lang;",
    "вЊЄ":"&rang;",
    "в—Љ":"&loz;",
    "в™ ":"&spades;",
    "в™Ј":"&clubs;",
    "в™Ґ":"&hearts;",
    "в™¦":"&diams;",
    // special chars
    "Е’":"&OElig;",
    "Е“":"&oelig;",
    "Е ":"&Scaron;",
    "ЕЎ":"&scaron;",
    "Её":"&Yuml;",
    "Л†":"&circ;",
    "Лњ":"&tilde;",
    "вЂ‚":"&ensp;",
    "вЂѓ":"&emsp;",
    "вЂ‰":"&thinsp;",
    "вЂЊ":"&zwnj;",
    "вЂЌ":"&zwj;",
    "вЂЋ":"&lrm;",
    "вЂЏ":"&rlm;",
    "вЂ“":"&ndash;",
    "вЂ”":"&mdash;",
    "вЂ":"&lsquo;",
    "вЂ™":"&rsquo;",
    "вЂљ":"&sbquo;",
    "вЂћ":"&bdquo;",
    "вЂ ":"&dagger;",
    "вЂЎ":"&Dagger;",
    "вЂ°":"&permil;",
    "вЂ№":"&lsaquo;",
    "вЂє":"&rsaquo;",
    "в‚¬":"&euro;",
    "вЂњ":"&ldquo;",
    "вЂќ":"&rdquo;"
  }
  var entities_str = "ВЎВўВЈВ¤ВҐВ¦В§ВЁВ©ВЄВ«В¬В­В®ВЇВ°В±ВІВіВґВµВ¶В·ВёВ№ВєВ»ВјВЅВѕВїГЂГЃГ‚ГѓГ„Г…Г†Г‡Г€Г‰ГЉГ‹ГЊГЌГЋГЏГђГ‘Г’Г“Г”Г•Г–Г—ГГ™ГљГ›ГњГќГћГџГ ГЎГўГЈГ¤ГҐГ¦Г§ГЁГ©ГЄГ«Г¬Г­Г®ГЇГ°Г±ГІГіГґГµГ¶Г·ГёГ№ГєГ»ГјГЅГѕГїЖ’О‘О’ОіО”О•О–О—ОО™ОљО›ОњОќОћОџО ОЎОЈО¤ОҐО¦О§ОЁО©О±ОІОіОґОµО¶О·ОёО№ОєО»ОјОЅОѕОїПЂПЃП‚ПѓП„П…П†П‡П€П‰вЂўвЂ¦вЂІвЂівЂѕвЃ„в„в„‘в„њв„ўв„µв†ђв†‘в†’в†“в†”в†µв‡ђв‡‘в‡’в‡”в€Ђв€‚в€ѓв€…в€‡в€€в€‰в€‹в€Џв€‘в€’в€—в€љв€ќв€ћв€§в€Ёв€©в€Єв€«в‰…в‰€в‰ в‰Ўв‰¤в‰ҐвЉ‚вЉѓвЉ„вЉ†вЉ‡вЉ•вЉ—вЉҐв‹…вЊ€вЊ‰вЊЉвЊ‹вЊ©вЊЄв—Љв™ в™Јв™Ґв™¦Е’Е“Е ЕЎЕёЛ†ЛњвЂ‚вЂѓвЂ‰вЂЊвЂЌвЂЋвЂЏвЂ“вЂ”вЂвЂ™вЂљвЂњвЂќвЂћвЂ вЂЎвЂ°вЂ№вЂєв‚¬";

  var rgx = new RegExp("[" + entities_str + "]", "gm");
  
  var matches = result.match(rgx);
  if (matches != null)
  {
    var processed = new Array();
    
    for (var i=0; i<matches.length; i++)
    {
      if (processed[matches[i]] == null && entities[matches[i]] != null && entities[matches[i]] != undefined)
      {
        // register that the symbol was processed
        processed[matches[i]] = entities[matches[i]];
        var replace_rgx = new RegExp(matches[i],"gm");
        result = result.replace(replace_rgx, entities[matches[i]]);
      }
    }    
  }
  
  return result;   
}